
<head>

<style type = "text/css">

h3 {
  padding-top: 0px;
}

</style>

</head>



```{r setup, echo=FALSE,results='hide', message=FALSE, warning=FALSE}

options(stringsAsFactors = FALSE)

# For the report
library(knitr)
library(mpmisc)
library(tbdbaid)

# For graphics
library(ggplot2)
library(gridExtra)
library(lubridate)

# For aggregation
library(plyr)
library(reshape2)


# Set default chunk options
opts_chunk$set(echo = FALSE,
               comment = "",
               message = FALSE,
               warning = FALSE,
               error = TRUE,
               fig.path = file.path("figure", x$prefix[1]),
               fig.width=8,
               fig.height=5.6,
               dpi=300,
               out.width="700px",
               dev="png",
               cache = FALSE)



# Set some plot parameters that will want tweaking
point_size <- 3
line_size <- 1.3
colorwheel <- c("#31A354", "#ADDD8E", "#F03B20", "#43A2CA")



# Get dates for the latest quarter, and for its corresponding quarter two
# years back
first.qtr <- get_quarter(Date = Sys.Date(), offset = -9)
last.qtr <- get_quarter(Date = Sys.Date(), offset = -1)


# Generate the full sequence of quarters that might be reported in
# the report - first.qtr goes back nine, but active tx completion
# actually goes back 12
qtr.seq <- sapply(seq(from = get_quarter(Date = Sys.Date(),
                                         offset = -12)$start.date,
                      to = last.qtr$end.date,
                      by = "3 months"),
                  simplify = "vector",
                  FUN = function(x) {

    # Extract the quarter label from the get_quarter results
    get_quarter(x)$qtr

})

    


# Set up a theme for all the plots
theme_tb <- theme_bw() +
            theme(legend.key.width = unit(.75, "inches"))




```




# Tuberculosis Control Activities for `r paste(x$hd_label[1])`
# `r last.qtr$qtr`
### Provided by the Denver Metro TB Control Program


## TB Cases in `r paste(x$county_label[1])`
-------------------------------------------

```{r case_plot}

# Get active cases over the last ten years.
# Ensure that the oldest year is a full year

actives <- query_actives(
    start_date = as.Date(paste(as.numeric(format(Sys.Date(), "%Y")) - 10,
                               "-01-01", 
                               sep = "")),
    stop_date = last.qtr$end.date)

countyactives <- subset(actives, report_county %in% x$county)



# Ensure the plot always extends back ten years, even if no cases then
this_year <- as.numeric(format(last.qtr$end.date, "%Y"))
ten_ago <- this_year - 10

# Make it a factor - this seems like the easiest way
countyactives$yr_plot <- factor(countyactives$yr_id,
                                levels = seq(ten_ago, this_year, 1),
                                ordered = TRUE)


# Plot it
ggplot(countyactives, aes(x = yr_plot)) +
    geom_bar(color = "black", fill = "#1F78B4") +
    stat_bin(geom="text", 
             aes(label=..count.., vjust = 1.25),
             color = "white") +
    expand_limits(y = c(0, 3)) +
    scale_x_discrete(drop = FALSE) +
    labs(x = "Year Identified", 
         y = "Number of cases",
         title = "Number of Active TB Cases by Year Identified") +
    theme_tb


```



```{r case_table,results='asis'}

actives_print <- ddply(countyactives, 
                       .var = "yr_plot", 
                       .drop = FALSE,
                       .fun = summarise,
                       total = length(report_county)
)


# Print it with nice names
names(actives_print) <- c("Year", "Total Cases")

dfprintif(actives_print)


```

## Patient Visits by Location
-------------------------------------------

```{r visits_inout}


# Query visits in the period and add the county of residence
visits <- add_county(query_visits(start_date = first.qtr$start.date,
                                  stop_date = last.qtr$end.date))

# Subset to just visits from residents of the current county
visits_co <- subset(visits, county %in% x$county)


# Add a plot quarter label
visits_co$plot_qtr <- with(visits_co, 

    # Make it a factor
    factor(paste(visit_yr, " Q", visit_qtr, sep = ""),
           levels = qtr.seq[4:12],
           ordered = TRUE)

)


# Aggregate by quarter and location
locagg <- count(subset(visits_co, location %in% c("Clinic", "Outreach")),
                vars = c("plot_qtr", "location"))


# Aggregate by just quarter to get a total visits count
qtragg <- count(subset(visits_co, location %in% c("Clinic", "Outreach")),
                vars = "plot_qtr")

# Label it
qtragg$location <- "All Visits"


# Combine them
visitagg <- rbind(locagg, qtragg)


# Plot it
ggplot(visitagg, aes(x = plot_qtr, 
                     y = freq, 
                     group = location, 
                     color = location)) +
    geom_point(size = point_size) +
    geom_line(aes(linetype = location), size = line_size) +
    expand_limits(y = 0) +
    scale_x_discrete(breaks = qtr.seq[4:12], drop = FALSE) +
    scale_color_manual("Visit Location", values = colorwheel[1:3]) +
    scale_linetype_discrete("Visit Location") +
    labs(x = "Visit date", 
         y = "Number of visits") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, 
                                                hjust = 1.30, 
                                                vjust = 1.3))


```


```{r visits_table, results='asis'}

# Cast visits wide
visits_wide <- dcast(visitagg, plot_qtr ~ location, value.var = "freq")

# Pretty-print
names(visits_wide) <- c("Quarter", "Total Visits", "Clinic Visits", "Outreach Visits")

dfprintif(visits_wide)

```



## Screenings for Active and Latent Tuberculosis
-------------------------------------------
```{r screens}

# Query test results for the period
tests <- add_county(query_tests(start_date = first.qtr$start.date,
                                stop_date = last.qtr$end.date))


# Subset to just this county's screenings
tests_co <- subset(tests, county %in% x$county)

# Convert date to quarter
tests_co$plot_qtr <- with(tests_co, 
                          
    # Make it a factor
    factor(paste(test_yr, " Q", test_qtr, sep = ""),
           levels = qtr.seq[4:12],
           ordered = TRUE)

)


# Aggregate by quarter
testagg <- count(tests_co, vars = c("test", "plot_qtr"))


# Plot it
ggplot(testagg, aes(x = plot_qtr, y = freq, group = test, color = test)) +
    geom_point(size = point_size) +
    geom_line(aes(linetype = test), size = line_size) +
    expand_limits(y = 0) +
    scale_x_discrete(breaks = qtr.seq[4:12], drop = FALSE) +
    scale_color_manual("Diagnostic", values = colorwheel[1:3]) +
    scale_linetype_discrete("Diagnostic") +
    labs(x = "Diagnostic date", 
         y = "Number of diagnostics") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, 
                                                hjust = 1.30, 
                                                vjust = 1.3))

```


```{r screens_table, results='asis'}

# Cast tests wide
tests_wide <- dcast(testagg, plot_qtr ~ test, value.var = "freq")

# Pretty-print
names(tests_wide) <- c("Quarter", "CXRs", "QFTs", "TSTs")

dfprintif(tests_wide)

```





## Treatment Initiation and Completion
-------------------------------------------

```{r plan_start}

# Get the plan starts from the last 9 quarters
plan_starts <- add_county(
    query_tx_plans(start_date = get_quarter(Date = Sys.Date(),
                                            offset = -9)$start.date,
                   stop_date = get_quarter(Date = Sys.Date(),
                                           offset = -1)$end.date)
)


# Subset to just plans from that county
plan_starts_co <- subset(plan_starts, county %in% x$county)


# Create a quarter label
plan_starts_co$plot_qtr <- with(plan_starts_co, paste(plan_yr, " Q", plan_qtr, sep = ""))

plan_summary <- ddply(plan_starts_co, 
                      .var = "plot_qtr", 
                      .drop = FALSE,
                      .fun = summarise,

                      Active = sum(treat_plan_type %in% "Active"),
                      LTBI = sum(treat_plan_type %in% "LTBI")
)


```





### Treatment Plans Initiated by Type

```{r tx_init}

plan_melt <- melt(plan_summary, id.var = "plot_qtr")

act_ltbi_init <- subset(plan_melt, variable %in% c("Active", "LTBI"))


# Convert the plot_qtr variable to a factor
act_ltbi_init$plot_qtr <- with(act_ltbi_init,

    # Make it a factor
    factor(plot_qtr,
           levels = qtr.seq[4:12],
           ordered = TRUE)

)


ggplot(act_ltbi_init, aes(x = plot_qtr, y = value, group = variable, color = variable)) +
    geom_point(size = point_size) +
    geom_line(aes(linetype = variable), size = line_size) +
    expand_limits(y = 0) +
    scale_x_discrete(breaks = qtr.seq[4:12], drop = FALSE) +
    scale_color_manual("Plan Type", values = colorwheel[1:2]) +
    scale_linetype_manual("Plan Type", values = c(1, 2)) +
    labs(x = "Quarter initiated", 
         y = "Number of patients") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, 
                                                hjust = 1.30, 
                                                vjust = 1.3))

```



```{r tx_init_table, results='asis'}

# Pretty names
names(plan_summary) <- c("Quarter", "Active", "LTBI")

dfprintif(plan_summary)



```


### Completion of Active Therapy

```{r active_comp}


# Query plans again for completion rates, shifting the window back 
# three quarters; those nine months allow for active and INH completion.
latest_plans <- add_county(
    query_latest_plans(start_date = get_quarter(Date = Sys.Date(),
                                                offset = -12)$start.date,
                       stop_date = get_quarter(Date = Sys.Date(),
                                               offset = -4)$end.date)
)


# County plans only
latest_plans_co <- subset(latest_plans, county %in% x$county)


# Create a quarter label
latest_plans_co$plot_qtr <- with(latest_plans_co, 

    # Make it a factor
    factor(paste(plan_yr, " Q", plan_qtr, sep = ""),
           levels = qtr.seq[1:9],
           ordered = TRUE)

)


# Calculate completion rates for active tx
act_comp <- ddply(subset(latest_plans_co, treat_plan_type %in% "Active"),
                 .var = "plot_qtr", 
                 .drop = FALSE,
                 .fun = summarise,

                 n = sum(completion_status %in% c("Completed", 
                                                  "Not Completed", 
                                                  "Ongoing")),
                 n_complete = sum(completion_status %in% "Completed"),
                 n_incomplete = sum(completion_status %in% "Not Completed"),
                 n_ongoing = sum(completion_status %in% "Ongoing"),
                 per_complete = calc_percent(n_complete, n, digits = 2)
                 
)


# Pull in the national averages and national targets
nat_avg <- read.csv(file.path("data", "ntip_stats.csv"))

# Add the quarter label
nat_avg$plot_qtr <- with(nat_avg, paste(year, " Q", qtr, sep = ""))

# Subset to only the quarters in the Denver data
nat_avg_sub <- subset(nat_avg, plot_qtr %in% qtr.seq[1:9])

# Melt it so that average and target are separate records
nat_melt <- melt(nat_avg_sub, 
                 id.var = "plot_qtr", 
                 measure.var = c("national_average", "target_2015"))


# Tidy up the variable labels and column names for stacking
nat_melt$variable <- as.character(nat_melt$variable)

nat_melt$variable[nat_melt$variable %in% "national_average"] <- 
    "National Average*"

nat_melt$variable[nat_melt$variable %in% "target_2015"] <- 
    "National 2015 Target* (93%)"

act_comp$variable <- paste(x$hd_tag[1], "Active TB Patients")

names(nat_melt)[names(nat_melt) %in% "value"] <- "per_complete"

nat_melt$n <- median(act_comp$n, na.rm = TRUE) + 1


# Combine our data, the national average, and the national targets
act_plot <- rbind(act_comp[ , c("plot_qtr", "n", "per_complete", "variable")],
                  nat_melt)




# Determine appropriate point size breaks
# Breaks are by one when maximum n is less than 10, and by
# max mod 5 when larger than 10
act_breaks <- seq(from = min(act_plot$n, na.rm = TRUE),
              to = max(act_plot$n, na.rm = TRUE),
              by = max(1, max(act_plot$n, na.rm = TRUE) %/% 5)
)


# Plot it
ggplot(act_plot, aes(x = plot_qtr, 
                     y = as.numeric(per_complete), 
                     color = variable, 
                     group = variable)) +
    geom_point(aes(size = as.integer(n))) +
    geom_line(aes(linetype = variable), size = line_size) +
    expand_limits(y = c(0, 100)) +
    scale_x_discrete(breaks = qtr.seq[1:9], drop = FALSE) +
    scale_color_manual("Statistic", values = colorwheel[1:3]) +
    scale_size_continuous("Number of Patients",
                          limits = c(1, max(act_plot$n, na.rm = TRUE)),
                          breaks = act_breaks) +
    scale_linetype_discrete("Statistic") +
    labs(x = "Quarter",
         y = "Percent Completed") +
       theme_tb + theme(axis.text.x = element_text(angle = 70, 
                                                   hjust = 1.30, 
                                                   vjust = 1.3))


```


```{r active_comp_table, results='asis'}

# Set up a version to print
act_print <- act_comp[ , c("plot_qtr", "n", 
                           "n_complete", "n_incomplete", 
                           "n_ongoing", "per_complete")]


# Pretty names
names(act_print) <- c("Quarter", "N Started", 
                      "N Completed", "N Not Completed", 
                      "N Ongoing", "% Complete")


dfprintif(act_print)



```



### Completion of LTBI Therapy


```{r ltbi_comp}

# Exclude any INH/Rifpentine plans before 2012
plans_trim <- 
    latest_plans_co[!(latest_plans_co$ltbi_drug %in% "INH/Rifapentine" & 
                      latest_plans_co$plan_yr < 2012), ]


# Calculate completion rates for latent tx
ltbi_comp <- ddply(subset(plans_trim, 
                          ltbi_drug %in% c("RIF", "INH", "INH/Rifapentine")),
                   .var = "plot_qtr",
                   .drop = FALSE,
                   .fun = summarise,
                   
           n = sum(completion_status %in% c("Completed", 
                                            "Not Completed", 
                                            "Ongoing")),
           n_complete = sum(completion_status %in% "Completed"),
           n_incomplete = sum(completion_status %in% "Not Completed"),
           n_ongoing = sum(completion_status %in% "Ongoing"),
           per_complete = calc_percent(n_complete, n, digits = 2),
           per_incomplete = calc_percent(n_incomplete, n, digits = 2),
           per_ongoing = calc_percent(n_ongoing, n, digits = 2)
)


# Add a label for plotting
ltbi_comp$label <- paste(x$hd_tag[1], "LTBI Patients")

# Add the national target
ltbi_plot <- rbind(ltbi_comp[ , c("plot_qtr", "label", "n", "per_complete")],
                   data.frame(plot_qtr = sort(unique(ltbi_comp[ , "plot_qtr"])),
                              label = "National 2015 Target* (79%)",
                              n = median(ltbi_comp$n, na.rm = TRUE) + 1,
                              per_complete = 79)
)

# Determine appropriate point size breaks
# Breaks are by one when maximum n is less than 10, and by
# max mod 5 when larger than 10
ltbi_breaks <- seq(from = min(ltbi_plot$n, na.rm = TRUE),
              to = max(ltbi_plot$n, na.rm = TRUE),
              by = max(1, max(ltbi_plot$n, na.rm = TRUE) %/% 5)
)


# Plot it
ggplot(ltbi_plot, aes(x = plot_qtr, 
                      y = as.numeric(per_complete),
                      group = label,
                      color = label)) +
    geom_point(aes(size = n)) +
    geom_line(aes(linetype = label), size = line_size) +
    expand_limits(y = c(0, 100)) +
    scale_x_discrete(breaks = qtr.seq[1:9], drop = FALSE) +
    scale_color_manual("Regimen", values = colorwheel[1:4]) +
    scale_size_continuous("Number of Patients",
                          limits = c(1, max(ltbi_plot$n, na.rm = TRUE)),
                          breaks = ltbi_breaks) +
    scale_linetype_discrete("Regimen") +
    labs(x = "Quarter",
         y = "Percent Completed") +
    theme_tb + theme(axis.text.x = element_text(angle = 70, 
                                                hjust = 1.30, 
                                                vjust = 1.3))


```

```{r ltbi_comp_table, results='asis'}

# Set up a version to print
ltbi_print <- ltbi_comp[ , c("plot_qtr", "n", 
                             "n_complete", "per_complete", 
                             "n_incomplete", "per_incomplete",
                             "n_ongoing", "per_ongoing")]


# Pretty names
names(ltbi_print) <- c("Quarter", "N Started", 
                       "N Completed", "% Complete",
                       "N Not Completed", "% Not Completed",
                       "N Ongoing", "% Ongoing")


dfprintif(ltbi_print)



```




```{r cleanup}



```


Generated at `r paste(Sys.time())`
